#!/bin/sh

PRG="shnake"

die(){
    show_cursor
    echo "$PRG: \033[1;31merror:\033[0m \033[1;37m$*\033[0m" >&2 # print to stderr
    exit 1
}

move_cursor(){
    if [ "$#" -ne 2 ]; then
        die "Incorrect number of args passed to move_cursor"
    fi
    printf "\033[%d;%dH" "$2" "$1"
}

show_cursor(){
    printf "\033[?25h"
}

hide_cursor(){
    printf "\033[?25l"
}

main(){
    hide_cursor

    show_cursor
}

main
